[build]
  command = ""
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[dev]
  functions = "netlify/functions"
  port = 8888

[[redirects]]
  from = "/api/team"
  to = "/.netlify/functions/team"
  status = 200

[[redirects]]
  from = "/api/admin"
  to = "/.netlify/functions/admin"
  status = 200
